[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mantle_sepolia = "https://rpc.sepolia.mantle.xyz"

[etherscan]
mantle_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.sepolia.mantle.xyz", chainId = 5003 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
